name: Deploy Sphinx Documentation

permissions:
  contents: write

# Trigger the workflow on push to the main branch
on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Check out the repository
      - name: Checkout repository
        uses: actions/checkout@v3

      # Step 2: Set up Python environment
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      # Step 3: Install Sphinx and dependencies
      - name: Install Python dependencies
        run: |
          pip install sphinx
          pip install sphinx-rtd-theme  # Or your preferred Sphinx theme
          pip install -r requirements.txt  # If you have a requirements file

      # Step 4: Build Sphinx documentation (HTML only)
      - name: Build HTML documentation
        run: sphinx-build -b html docs/ source/_build/html

      # Step 5: Deploy to GitHub Pages
      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: docs/_build/html
